version: '3'

services:

  arduino-ide:
    image: arduino-ide.local

    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_SRC: dockyland/arduino-ide:2.2.1
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        PLUGDEV_GROUP_ID: ${PLUGDEV_GROUP_ID}
        DIALOUT_GROUP_ID: ${DIALOUT_GROUP_ID}

    container_name: arduino-ide-container

    network_mode: host

    privileged: true

    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - ${PWD}/workspace:/workspace
      - arduino15:/home/docky/.arduino15
      - arduinoIDE:/home/docky/.arduinoIDE
    
    command: sh -c "arduino-cli core update-index --config-file=/home/docky/.arduino15/arduino-cli.yaml && xargs -n 2 arduino-cli core install --config-file=/home/docky/.arduino15/arduino-cli.yaml < /workspace/arduino-packages.txt && arduino-cli core list && arduino-ide"

volumes:
  arduino15:
  arduinoIDE: